AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

Layout/ArgumentAlignment:
  # Alignment of arguments in multi-line method calls.
  #
  # The `with_fixed_indentation` style aligns the following lines with one
  # level of indentation relative to the start of the line with the method call.
  #
  #     method_call(a,
  #       b)
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120 # Default: 80

Layout/ParameterAlignment:
  # Alignment of parameters in multi-line method definition.
  #
  # The `with_fixed_indentation` style aligns the following lines with one
  # level of indentation relative to the start of the line with the method call.
  #
  #     def method_foo(a,
  #       b)
  EnforcedStyle: with_fixed_indentation

Lint/MissingSuper:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Metrics/ClassLength:
  Max: 200 # Default: 100

Metrics/MethodLength:
  Max: 20 # Default: 10

Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*.rb

Naming/FileName:
  Exclude:
    - spec/gemfiles/*

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional # Default: disallowed

Style/Documentation:
  # This cop checks for missing top-level documentation of classes and modules.
  # Classes with no body and namespace modules are exempt from the check.
  # Namespace modules are modules that have nothing in their bodies except
  # classes or other modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - spec/**/*.rb
