dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.7
  - 3.0
  - 3.1
  - 3.2

gemfile:
  - spec/gemfiles/rails-6.0.gemfile
  - spec/gemfiles/rails-6.1.gemfile
  - spec/gemfiles/rails-7.0.gemfile
  - spec/gemfiles/rails-7.1.gemfile

before_install: gem update bundler
bundler_args: --jobs 3
install: bundle install --jobs 3

script:
  - bash -c "if [ '$TRAVIS_RUBY_VERSION' = '2.7' ] && [[ '$BUNDLE_GEMFILE' == *'rails-6.1'* ]]; then bundle exec rubocop --fail-level autocorrect; fi"
  - bundle exec rspec
